### ISSUE TITLE
User hostnames a little messed up

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/kiwibnc#9]
In kiwi the hostname doesnt get detected. While in textual the nicklist shows the hostnames inline for some users:
![image](https://user-images.githubusercontent.com/725880/57253616-0e838500-7047-11e9-938a-12ea8f82582a.png)

**Comment by prawnsalad** [comment]
Shown by beerbarian in #kiwiirc, on freenode it does actually show:
![image](https://user-images.githubusercontent.com/725880/57254224-99b14a80-7048-11e9-85a8-c0cf6ab4dd31.png)

**Comment by DanielOaks** [comment]
Hmm, I think I can see where this is happening yeah. Will update here once confirmed.

**Comment by DanielOaks** [comment]
I've got kiwibnc setup to connect to freenode and join the `#kiwiirc` channel. I've got both Kiwi and Textual hooked up to the bnc and the userlist shows only the nicknames as expected. I've asked in the channel to see whether there's any additional info for when this shows up, any other more specific installs that I should test out, etc.

@prawnsalad correct me if I'm wrong, but that Kiwi screenshot looks like it's just showing the user@host in a separate little section underneath the nick when you click on a user, which seems to be expected behaviour?

**Comment by prawnsalad** [comment]
I've just been retesting this issue and I can't replicate it anymore. Unsure if commits since have fixed the issue...

Testing a bit more throughout today and will close this if I can't reproduce it.

**Comment by DanielOaks** [comment]
Definitely, give us a shout if you do fine any cases and I can submit a PR.

**Comment by DanielOaks** [comment]
Can't reproduce this, we'll open a new issue if we see it again
